smtp-data:
  image: loophole/smtp-data
syslog:
  image: loophole/syslog
  volumes:
    - /tmp/syslogdev:/dev
smtp:
  image: loophole/smtp-private
  volumes_from:
    - smtp-data
  volumes:
    - /tmp/syslogdev/log:/var/spool/postfix/dev/log
  environment:
    mydestination: housh.email
  ports:
    - "25:25"
sshd:
  image: loophole/sshd-private
  volumes_from:
    - smtp-data
  ports:
    - "2697:22"
